from __future__ import annotations

from sqlalchemy import ForeignKey
from sqlalchemy import String
from sqlalchemy import Text
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship

from models.base_model import BaseModel


class AIReport(BaseModel):
    """
    Stores AI analysis reports generated by Gemini.
    """

    __tablename__ = "ai_reports"

    # ==========================================================
    # Foreign Keys
    # ==========================================================

    pet_id: Mapped[int] = mapped_column(
        ForeignKey("pets.id"),
        nullable=False,
        index=True,
    )

    pet_image_id: Mapped[int] = mapped_column(
        ForeignKey("pet_images.id"),
        nullable=False,
        index=True,
    )

    # ==========================================================
    # AI Data
    # ==========================================================

    model_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    symptoms: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    report: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    confidence: Mapped[str | None] = mapped_column(
        String(30),
        nullable=True,
    )

    # ==========================================================
    # Relationships
    # ==========================================================

    pet = relationship(
        "Pet",
        back_populates="ai_reports",
    )

    pet_image = relationship(
        "PetImage",
        back_populates="ai_reports",
    )

    def __repr__(self) -> str:
        return (
            f"<AIReport("
            f"id={self.id}, "
            f"pet_id={self.pet_id}, "
            f"pet_image_id={self.pet_image_id}"
            f")>"
        )